nba:
  target: dev
  outputs:
    dev:
      dbname: nba
      host: localhost
      pass: ap00AP42!
      port: 5432
      schema: dev
      threads: 16
      type: postgres
      user: postgres
    production:
      dbname: nba
      host: localhost
      pass: ap00AP42!
      port: 5432
      schema: continuous_integration
      threads: 16
      type: postgres
      user: postgres    
    production:
      dbname: nba
      host: localhost
      pass: ap00AP42!
      port: 5432
      schema: production
      threads: 16
      type: postgres
      user: postgres    
